apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  hostpath-pvc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local